version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: dockerfile_backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./
      dockerfile: dockerfile_frontend
    ports:
      - "80:7000"